--TEST--
setProperties + setCustomProperty: all 4 custom-property types accepted
--SKIPIF--
<?php if (!extension_loaded("xlswriter")) print "skip"; ?>
--FILE--
<?php
$config = ['path' => './tests'];

$path = (new \Vtiful\Kernel\Excel($config))
    ->fileName('set_properties.xlsx')
    ->setProperties([
        'title'          => 'Quarterly Report',
        'author'         => 'A. Tester',
        'manager'        => 'Manager',
        'company'        => 'Acme',
        'category'       => 'Sales',
        'keywords'       => 'q1,q2',
        'comments'       => 'Generated by phpunit',
        'subject'        => 'Subj',
        'status'         => 'Draft',
        'hyperlink_base' => 'https://example.com',
    ])
    ->setCustomProperty('Reviewed by', 'Eve')
    ->setCustomProperty('Doc number',  12345)
    ->setCustomProperty('Has Review',  true)
    ->setCustomProperty('Created at',  1700000000, 'datetime')
    ->insertText(0, 0, 'x')
    ->output();

var_dump(is_file($path));
?>
--CLEAN--
<?php
@unlink(__DIR__ . '/set_properties.xlsx');
?>
--EXPECT--
bool(true)
