--TEST--
Check for vtiful presence
--SKIPIF--
<?php if (!extension_loaded("xlswriter")) print "skip"; ?>
--FILE--
<?php
$config = ['path' => './tests'];

$path = (new \Vtiful\Kernel\Excel($config))
    ->fileName('set_properties.xlsx')
    ->setProperties([
        'title'          => 'Quarterly Report',
        'author'         => 'A. Tester',
        'manager'        => 'Manager',
        'company'        => 'Acme',
        'category'       => 'Sales',
        'keywords'       => 'q1,q2',
        'comments'       => 'Generated by phpunit',
        'subject'        => 'Subj',
        'status'         => 'Draft',
        'hyperlink_base' => 'https://example.com',
    ])
    ->setCustomProperty('Reviewed by', 'Eve')
    ->setCustomProperty('Doc number',  12345)
    ->setCustomProperty('Has Review',  true)
    ->setCustomProperty('Created at',  1700000000, 'datetime')
    ->insertText(0, 0, 'x')
    ->output();

var_dump(is_file($path));

/* Round-trip: setProperties values land in docProps/core.xml + app.xml, and
 * setCustomProperty values land in docProps/custom.xml. No reader API; probe
 * the raw OOXML. */
$core   = shell_exec('unzip -p ' . escapeshellarg($path) . ' docProps/core.xml');
$app    = shell_exec('unzip -p ' . escapeshellarg($path) . ' docProps/app.xml');
$custom = shell_exec('unzip -p ' . escapeshellarg($path) . ' docProps/custom.xml');

function tag($xml, $tag) {
    return preg_match('#<' . preg_quote($tag, '#') . '[^>]*>([^<]*)</#', $xml, $m) ? $m[1] : '';
}
echo "core.title: "    . tag($core, 'dc:title')        . "\n";
echo "core.author: "   . tag($core, 'dc:creator')      . "\n";
echo "core.subject: "  . tag($core, 'dc:subject')      . "\n";
echo "core.keywords: " . tag($core, 'cp:keywords')     . "\n";
echo "core.status: "   . tag($core, 'cp:contentStatus'). "\n";
echo "app.manager: "   . tag($app,  'Manager')         . "\n";
echo "app.company: "   . tag($app,  'Company')         . "\n";

/* Custom properties (4 of them) preserve names AND values per spec type. */
preg_match_all('/<property[^>]*\sname="([^"]+)"[^>]*>(.*?)<\/property>/', $custom, $m);
foreach ($m[1] as $i => $n) echo "custom.$n: " . strip_tags($m[2][$i]) . "\n";
?>
--CLEAN--
<?php
@unlink(__DIR__ . '/set_properties.xlsx');
?>
--EXPECT--
bool(true)
core.title: Quarterly Report
core.author: A. Tester
core.subject: Subj
core.keywords: q1,q2
core.status: Draft
app.manager: Manager
app.company: Acme
custom.Reviewed by: Eve
custom.Doc number: 12345
custom.Has Review: true
custom.Created at: 2023-11-14T22:13:20Z
